// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: plugin/v1/plugin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GatewayDPluginService_GetPluginConfig_FullMethodName     = "/plugin.v1.GatewayDPluginService/GetPluginConfig"
	GatewayDPluginService_OnConfigLoaded_FullMethodName      = "/plugin.v1.GatewayDPluginService/OnConfigLoaded"
	GatewayDPluginService_OnNewLogger_FullMethodName         = "/plugin.v1.GatewayDPluginService/OnNewLogger"
	GatewayDPluginService_OnNewPool_FullMethodName           = "/plugin.v1.GatewayDPluginService/OnNewPool"
	GatewayDPluginService_OnNewClient_FullMethodName         = "/plugin.v1.GatewayDPluginService/OnNewClient"
	GatewayDPluginService_OnNewProxy_FullMethodName          = "/plugin.v1.GatewayDPluginService/OnNewProxy"
	GatewayDPluginService_OnNewServer_FullMethodName         = "/plugin.v1.GatewayDPluginService/OnNewServer"
	GatewayDPluginService_OnSignal_FullMethodName            = "/plugin.v1.GatewayDPluginService/OnSignal"
	GatewayDPluginService_OnRun_FullMethodName               = "/plugin.v1.GatewayDPluginService/OnRun"
	GatewayDPluginService_OnBooting_FullMethodName           = "/plugin.v1.GatewayDPluginService/OnBooting"
	GatewayDPluginService_OnBooted_FullMethodName            = "/plugin.v1.GatewayDPluginService/OnBooted"
	GatewayDPluginService_OnOpening_FullMethodName           = "/plugin.v1.GatewayDPluginService/OnOpening"
	GatewayDPluginService_OnOpened_FullMethodName            = "/plugin.v1.GatewayDPluginService/OnOpened"
	GatewayDPluginService_OnClosing_FullMethodName           = "/plugin.v1.GatewayDPluginService/OnClosing"
	GatewayDPluginService_OnClosed_FullMethodName            = "/plugin.v1.GatewayDPluginService/OnClosed"
	GatewayDPluginService_OnTraffic_FullMethodName           = "/plugin.v1.GatewayDPluginService/OnTraffic"
	GatewayDPluginService_OnTrafficFromClient_FullMethodName = "/plugin.v1.GatewayDPluginService/OnTrafficFromClient"
	GatewayDPluginService_OnTrafficToServer_FullMethodName   = "/plugin.v1.GatewayDPluginService/OnTrafficToServer"
	GatewayDPluginService_OnTrafficFromServer_FullMethodName = "/plugin.v1.GatewayDPluginService/OnTrafficFromServer"
	GatewayDPluginService_OnTrafficToClient_FullMethodName   = "/plugin.v1.GatewayDPluginService/OnTrafficToClient"
	GatewayDPluginService_OnShutdown_FullMethodName          = "/plugin.v1.GatewayDPluginService/OnShutdown"
	GatewayDPluginService_OnTick_FullMethodName              = "/plugin.v1.GatewayDPluginService/OnTick"
	GatewayDPluginService_OnHook_FullMethodName              = "/plugin.v1.GatewayDPluginService/OnHook"
)

// GatewayDPluginServiceClient is the client API for GatewayDPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayDPluginServiceClient interface {
	// GetPluginConfig returns the plugin config upon registration
	GetPluginConfig(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnConfigLoaded is called when the config is loaded from any config provider
	OnConfigLoaded(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnNewLogger is called when a new logger is created
	OnNewLogger(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnNewPool is called when a new pool is created
	OnNewPool(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnNewClient is called when a new client is created
	OnNewClient(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnNewProxy is called when a new proxy is created
	OnNewProxy(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnNewServer is called when a new server is created
	OnNewServer(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnSignal is called when an OS signal is received
	OnSignal(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnRun is called when the gatewayd server is running
	OnRun(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnBooting is called when the gatewayd server is booting
	OnBooting(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnBooted is called when the gatewayd server is booted
	OnBooted(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnOpening is called when the gatewayd server is opening
	OnOpening(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnOpened is called when the gatewayd server is opened
	OnOpened(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnClosing is called when the gatewayd server is closing
	OnClosing(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnClosed is called when the gatewayd server is closed
	OnClosed(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnTraffic is called when the gatewayd server received traffic from a client
	OnTraffic(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnTrafficFromClient is called when the gatewayd server is receiving traffic from a client
	OnTrafficFromClient(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnTrafficToServer is called when the gatewayd server is sending traffic to a server
	OnTrafficToServer(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnTrafficFromServer is called when the gatewayd server is receiving traffic from a server
	OnTrafficFromServer(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnTrafficToClient is called when the gatewayd server is sending traffic to a client
	OnTrafficToClient(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnShutdown is called when the gatewayd server is shutting down
	OnShutdown(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnTick is called when the gatewayd server is ticking
	OnTick(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
	// OnHook is called when the gatewayd server is calling a custom hook
	OnHook(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error)
}

type gatewayDPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayDPluginServiceClient(cc grpc.ClientConnInterface) GatewayDPluginServiceClient {
	return &gatewayDPluginServiceClient{cc}
}

func (c *gatewayDPluginServiceClient) GetPluginConfig(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_GetPluginConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnConfigLoaded(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnConfigLoaded_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnNewLogger(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnNewLogger_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnNewPool(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnNewPool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnNewClient(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnNewClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnNewProxy(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnNewProxy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnNewServer(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnNewServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnSignal(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnSignal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnRun(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnBooting(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnBooting_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnBooted(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnBooted_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnOpening(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnOpening_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnOpened(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnOpened_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnClosing(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnClosing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnClosed(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnClosed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnTraffic(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnTraffic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnTrafficFromClient(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnTrafficFromClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnTrafficToServer(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnTrafficToServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnTrafficFromServer(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnTrafficFromServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnTrafficToClient(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnTrafficToClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnShutdown(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnShutdown_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnTick(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnTick_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayDPluginServiceClient) OnHook(ctx context.Context, in *Struct, opts ...grpc.CallOption) (*Struct, error) {
	out := new(Struct)
	err := c.cc.Invoke(ctx, GatewayDPluginService_OnHook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayDPluginServiceServer is the server API for GatewayDPluginService service.
// All implementations must embed UnimplementedGatewayDPluginServiceServer
// for forward compatibility
type GatewayDPluginServiceServer interface {
	// GetPluginConfig returns the plugin config upon registration
	GetPluginConfig(context.Context, *Struct) (*Struct, error)
	// OnConfigLoaded is called when the config is loaded from any config provider
	OnConfigLoaded(context.Context, *Struct) (*Struct, error)
	// OnNewLogger is called when a new logger is created
	OnNewLogger(context.Context, *Struct) (*Struct, error)
	// OnNewPool is called when a new pool is created
	OnNewPool(context.Context, *Struct) (*Struct, error)
	// OnNewClient is called when a new client is created
	OnNewClient(context.Context, *Struct) (*Struct, error)
	// OnNewProxy is called when a new proxy is created
	OnNewProxy(context.Context, *Struct) (*Struct, error)
	// OnNewServer is called when a new server is created
	OnNewServer(context.Context, *Struct) (*Struct, error)
	// OnSignal is called when an OS signal is received
	OnSignal(context.Context, *Struct) (*Struct, error)
	// OnRun is called when the gatewayd server is running
	OnRun(context.Context, *Struct) (*Struct, error)
	// OnBooting is called when the gatewayd server is booting
	OnBooting(context.Context, *Struct) (*Struct, error)
	// OnBooted is called when the gatewayd server is booted
	OnBooted(context.Context, *Struct) (*Struct, error)
	// OnOpening is called when the gatewayd server is opening
	OnOpening(context.Context, *Struct) (*Struct, error)
	// OnOpened is called when the gatewayd server is opened
	OnOpened(context.Context, *Struct) (*Struct, error)
	// OnClosing is called when the gatewayd server is closing
	OnClosing(context.Context, *Struct) (*Struct, error)
	// OnClosed is called when the gatewayd server is closed
	OnClosed(context.Context, *Struct) (*Struct, error)
	// OnTraffic is called when the gatewayd server received traffic from a client
	OnTraffic(context.Context, *Struct) (*Struct, error)
	// OnTrafficFromClient is called when the gatewayd server is receiving traffic from a client
	OnTrafficFromClient(context.Context, *Struct) (*Struct, error)
	// OnTrafficToServer is called when the gatewayd server is sending traffic to a server
	OnTrafficToServer(context.Context, *Struct) (*Struct, error)
	// OnTrafficFromServer is called when the gatewayd server is receiving traffic from a server
	OnTrafficFromServer(context.Context, *Struct) (*Struct, error)
	// OnTrafficToClient is called when the gatewayd server is sending traffic to a client
	OnTrafficToClient(context.Context, *Struct) (*Struct, error)
	// OnShutdown is called when the gatewayd server is shutting down
	OnShutdown(context.Context, *Struct) (*Struct, error)
	// OnTick is called when the gatewayd server is ticking
	OnTick(context.Context, *Struct) (*Struct, error)
	// OnHook is called when the gatewayd server is calling a custom hook
	OnHook(context.Context, *Struct) (*Struct, error)
	mustEmbedUnimplementedGatewayDPluginServiceServer()
}

// UnimplementedGatewayDPluginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayDPluginServiceServer struct {
}

func (UnimplementedGatewayDPluginServiceServer) GetPluginConfig(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginConfig not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnConfigLoaded(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnConfigLoaded not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnNewLogger(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnNewLogger not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnNewPool(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnNewPool not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnNewClient(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnNewClient not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnNewProxy(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnNewProxy not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnNewServer(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnNewServer not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnSignal(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnSignal not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnRun(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnRun not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnBooting(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnBooting not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnBooted(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnBooted not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnOpening(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnOpening not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnOpened(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnOpened not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnClosing(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnClosing not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnClosed(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnClosed not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnTraffic(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTraffic not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnTrafficFromClient(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTrafficFromClient not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnTrafficToServer(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTrafficToServer not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnTrafficFromServer(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTrafficFromServer not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnTrafficToClient(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTrafficToClient not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnShutdown(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnShutdown not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnTick(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTick not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) OnHook(context.Context, *Struct) (*Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnHook not implemented")
}
func (UnimplementedGatewayDPluginServiceServer) mustEmbedUnimplementedGatewayDPluginServiceServer() {}

// UnsafeGatewayDPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayDPluginServiceServer will
// result in compilation errors.
type UnsafeGatewayDPluginServiceServer interface {
	mustEmbedUnimplementedGatewayDPluginServiceServer()
}

func RegisterGatewayDPluginServiceServer(s grpc.ServiceRegistrar, srv GatewayDPluginServiceServer) {
	s.RegisterService(&GatewayDPluginService_ServiceDesc, srv)
}

func _GatewayDPluginService_GetPluginConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).GetPluginConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_GetPluginConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).GetPluginConfig(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnConfigLoaded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnConfigLoaded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnConfigLoaded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnConfigLoaded(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnNewLogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnNewLogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnNewLogger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnNewLogger(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnNewPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnNewPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnNewPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnNewPool(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnNewClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnNewClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnNewClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnNewClient(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnNewProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnNewProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnNewProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnNewProxy(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnNewServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnNewServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnNewServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnNewServer(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnSignal(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnRun(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnBooting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnBooting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnBooting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnBooting(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnBooted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnBooted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnBooted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnBooted(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnOpening_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnOpening(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnOpening_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnOpening(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnOpened_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnOpened(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnOpened_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnOpened(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnClosing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnClosing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnClosing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnClosing(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnClosed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnClosed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnClosed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnClosed(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnTraffic(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnTrafficFromClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnTrafficFromClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnTrafficFromClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnTrafficFromClient(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnTrafficToServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnTrafficToServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnTrafficToServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnTrafficToServer(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnTrafficFromServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnTrafficFromServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnTrafficFromServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnTrafficFromServer(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnTrafficToClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnTrafficToClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnTrafficToClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnTrafficToClient(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnShutdown(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnTick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnTick(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayDPluginService_OnHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDPluginServiceServer).OnHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDPluginService_OnHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDPluginServiceServer).OnHook(ctx, req.(*Struct))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayDPluginService_ServiceDesc is the grpc.ServiceDesc for GatewayDPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayDPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.GatewayDPluginService",
	HandlerType: (*GatewayDPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPluginConfig",
			Handler:    _GatewayDPluginService_GetPluginConfig_Handler,
		},
		{
			MethodName: "OnConfigLoaded",
			Handler:    _GatewayDPluginService_OnConfigLoaded_Handler,
		},
		{
			MethodName: "OnNewLogger",
			Handler:    _GatewayDPluginService_OnNewLogger_Handler,
		},
		{
			MethodName: "OnNewPool",
			Handler:    _GatewayDPluginService_OnNewPool_Handler,
		},
		{
			MethodName: "OnNewClient",
			Handler:    _GatewayDPluginService_OnNewClient_Handler,
		},
		{
			MethodName: "OnNewProxy",
			Handler:    _GatewayDPluginService_OnNewProxy_Handler,
		},
		{
			MethodName: "OnNewServer",
			Handler:    _GatewayDPluginService_OnNewServer_Handler,
		},
		{
			MethodName: "OnSignal",
			Handler:    _GatewayDPluginService_OnSignal_Handler,
		},
		{
			MethodName: "OnRun",
			Handler:    _GatewayDPluginService_OnRun_Handler,
		},
		{
			MethodName: "OnBooting",
			Handler:    _GatewayDPluginService_OnBooting_Handler,
		},
		{
			MethodName: "OnBooted",
			Handler:    _GatewayDPluginService_OnBooted_Handler,
		},
		{
			MethodName: "OnOpening",
			Handler:    _GatewayDPluginService_OnOpening_Handler,
		},
		{
			MethodName: "OnOpened",
			Handler:    _GatewayDPluginService_OnOpened_Handler,
		},
		{
			MethodName: "OnClosing",
			Handler:    _GatewayDPluginService_OnClosing_Handler,
		},
		{
			MethodName: "OnClosed",
			Handler:    _GatewayDPluginService_OnClosed_Handler,
		},
		{
			MethodName: "OnTraffic",
			Handler:    _GatewayDPluginService_OnTraffic_Handler,
		},
		{
			MethodName: "OnTrafficFromClient",
			Handler:    _GatewayDPluginService_OnTrafficFromClient_Handler,
		},
		{
			MethodName: "OnTrafficToServer",
			Handler:    _GatewayDPluginService_OnTrafficToServer_Handler,
		},
		{
			MethodName: "OnTrafficFromServer",
			Handler:    _GatewayDPluginService_OnTrafficFromServer_Handler,
		},
		{
			MethodName: "OnTrafficToClient",
			Handler:    _GatewayDPluginService_OnTrafficToClient_Handler,
		},
		{
			MethodName: "OnShutdown",
			Handler:    _GatewayDPluginService_OnShutdown_Handler,
		},
		{
			MethodName: "OnTick",
			Handler:    _GatewayDPluginService_OnTick_Handler,
		},
		{
			MethodName: "OnHook",
			Handler:    _GatewayDPluginService_OnHook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/plugin.proto",
}
