// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/plugin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HookName int32

const (
	HookName_HOOK_NAME_UNSPECIFIED            HookName = 0
	HookName_HOOK_NAME_ON_CONFIG_LOADED       HookName = 1
	HookName_HOOK_NAME_ON_NEW_LOGGER          HookName = 2
	HookName_HOOK_NAME_ON_NEW_POOL            HookName = 3
	HookName_HOOK_NAME_ON_NEW_CLIENT          HookName = 4
	HookName_HOOK_NAME_ON_NEW_PROXY           HookName = 5
	HookName_HOOK_NAME_ON_NEW_SERVER          HookName = 6
	HookName_HOOK_NAME_ON_SIGNAL              HookName = 7
	HookName_HOOK_NAME_ON_RUN                 HookName = 8
	HookName_HOOK_NAME_ON_BOOTING             HookName = 9
	HookName_HOOK_NAME_ON_BOOTED              HookName = 10
	HookName_HOOK_NAME_ON_OPENING             HookName = 11
	HookName_HOOK_NAME_ON_OPENED              HookName = 12
	HookName_HOOK_NAME_ON_CLOSING             HookName = 13
	HookName_HOOK_NAME_ON_CLOSED              HookName = 14
	HookName_HOOK_NAME_ON_TRAFFIC             HookName = 15
	HookName_HOOK_NAME_ON_TRAFFIC_FROM_CLIENT HookName = 16
	HookName_HOOK_NAME_ON_TRAFFIC_TO_SERVER   HookName = 17
	HookName_HOOK_NAME_ON_TRAFFIC_FROM_SERVER HookName = 18
	HookName_HOOK_NAME_ON_TRAFFIC_TO_CLIENT   HookName = 19
	HookName_HOOK_NAME_ON_SHUTDOWN            HookName = 20
	HookName_HOOK_NAME_ON_TICK                HookName = 21
	HookName_HOOK_NAME_ON_HOOK                HookName = 22
)

// Enum value maps for HookName.
var (
	HookName_name = map[int32]string{
		0:  "HOOK_NAME_UNSPECIFIED",
		1:  "HOOK_NAME_ON_CONFIG_LOADED",
		2:  "HOOK_NAME_ON_NEW_LOGGER",
		3:  "HOOK_NAME_ON_NEW_POOL",
		4:  "HOOK_NAME_ON_NEW_CLIENT",
		5:  "HOOK_NAME_ON_NEW_PROXY",
		6:  "HOOK_NAME_ON_NEW_SERVER",
		7:  "HOOK_NAME_ON_SIGNAL",
		8:  "HOOK_NAME_ON_RUN",
		9:  "HOOK_NAME_ON_BOOTING",
		10: "HOOK_NAME_ON_BOOTED",
		11: "HOOK_NAME_ON_OPENING",
		12: "HOOK_NAME_ON_OPENED",
		13: "HOOK_NAME_ON_CLOSING",
		14: "HOOK_NAME_ON_CLOSED",
		15: "HOOK_NAME_ON_TRAFFIC",
		16: "HOOK_NAME_ON_TRAFFIC_FROM_CLIENT",
		17: "HOOK_NAME_ON_TRAFFIC_TO_SERVER",
		18: "HOOK_NAME_ON_TRAFFIC_FROM_SERVER",
		19: "HOOK_NAME_ON_TRAFFIC_TO_CLIENT",
		20: "HOOK_NAME_ON_SHUTDOWN",
		21: "HOOK_NAME_ON_TICK",
		22: "HOOK_NAME_ON_HOOK",
	}
	HookName_value = map[string]int32{
		"HOOK_NAME_UNSPECIFIED":            0,
		"HOOK_NAME_ON_CONFIG_LOADED":       1,
		"HOOK_NAME_ON_NEW_LOGGER":          2,
		"HOOK_NAME_ON_NEW_POOL":            3,
		"HOOK_NAME_ON_NEW_CLIENT":          4,
		"HOOK_NAME_ON_NEW_PROXY":           5,
		"HOOK_NAME_ON_NEW_SERVER":          6,
		"HOOK_NAME_ON_SIGNAL":              7,
		"HOOK_NAME_ON_RUN":                 8,
		"HOOK_NAME_ON_BOOTING":             9,
		"HOOK_NAME_ON_BOOTED":              10,
		"HOOK_NAME_ON_OPENING":             11,
		"HOOK_NAME_ON_OPENED":              12,
		"HOOK_NAME_ON_CLOSING":             13,
		"HOOK_NAME_ON_CLOSED":              14,
		"HOOK_NAME_ON_TRAFFIC":             15,
		"HOOK_NAME_ON_TRAFFIC_FROM_CLIENT": 16,
		"HOOK_NAME_ON_TRAFFIC_TO_SERVER":   17,
		"HOOK_NAME_ON_TRAFFIC_FROM_SERVER": 18,
		"HOOK_NAME_ON_TRAFFIC_TO_CLIENT":   19,
		"HOOK_NAME_ON_SHUTDOWN":            20,
		"HOOK_NAME_ON_TICK":                21,
		"HOOK_NAME_ON_HOOK":                22,
	}
)

func (x HookName) Enum() *HookName {
	p := new(HookName)
	*p = x
	return p
}

func (x HookName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HookName) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (HookName) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[0]
}

func (x HookName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HookName.Descriptor instead.
func (HookName) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	RemoteUrl     string                 `protobuf:"bytes,3,opt,name=remote_url,json=remoteUrl,proto3" json:"remote_url,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginID) Reset() {
	*x = PluginID{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginID) ProtoMessage() {}

func (x *PluginID) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginID.ProtoReflect.Descriptor instead.
func (*PluginID) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginID) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginID) GetRemoteUrl() string {
	if x != nil {
		return x.RemoteUrl
	}
	return ""
}

func (x *PluginID) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type PluginConfig struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *PluginID              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Authors     []string               `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"`
	License     string                 `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`
	ProjectUrl  string                 `protobuf:"bytes,5,opt,name=project_url,json=projectUrl,proto3" json:"project_url,omitempty"`
	// internal and external config options
	Config map[string]string `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// hooks it attaches to
	Hooks []HookName `protobuf:"varint,7,rep,packed,name=hooks,proto3,enum=plugin.v1.HookName" json:"hooks,omitempty"`
	// required plugins
	Requires      map[string]string `protobuf:"bytes,8,rep,name=requires,proto3" json:"requires,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string          `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Categories    []string          `protobuf:"bytes,10,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginConfig.ProtoReflect.Descriptor instead.
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginConfig) GetId() *PluginID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PluginConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginConfig) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *PluginConfig) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *PluginConfig) GetProjectUrl() string {
	if x != nil {
		return x.ProjectUrl
	}
	return ""
}

func (x *PluginConfig) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PluginConfig) GetHooks() []HookName {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *PluginConfig) GetRequires() map[string]string {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *PluginConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PluginConfig) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/plugin.proto\x12\tplugin.v1\x1a\x16plugin/v1/struct.proto\"s\n" +
	"\bPluginID\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"remote_url\x18\x03 \x01(\tR\tremoteUrl\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"\x81\x04\n" +
	"\fPluginConfig\x12#\n" +
	"\x02id\x18\x01 \x01(\v2\x13.plugin.v1.PluginIDR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aauthors\x18\x03 \x03(\tR\aauthors\x12\x18\n" +
	"\alicense\x18\x04 \x01(\tR\alicense\x12\x1f\n" +
	"\vproject_url\x18\x05 \x01(\tR\n" +
	"projectUrl\x12;\n" +
	"\x06config\x18\x06 \x03(\v2#.plugin.v1.PluginConfig.ConfigEntryR\x06config\x12)\n" +
	"\x05hooks\x18\a \x03(\x0e2\x13.plugin.v1.HookNameR\x05hooks\x12A\n" +
	"\brequires\x18\b \x03(\v2%.plugin.v1.PluginConfig.RequiresEntryR\brequires\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"categories\x18\n" +
	" \x03(\tR\n" +
	"categories\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rRequiresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x92\x05\n" +
	"\bHookName\x12\x19\n" +
	"\x15HOOK_NAME_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aHOOK_NAME_ON_CONFIG_LOADED\x10\x01\x12\x1b\n" +
	"\x17HOOK_NAME_ON_NEW_LOGGER\x10\x02\x12\x19\n" +
	"\x15HOOK_NAME_ON_NEW_POOL\x10\x03\x12\x1b\n" +
	"\x17HOOK_NAME_ON_NEW_CLIENT\x10\x04\x12\x1a\n" +
	"\x16HOOK_NAME_ON_NEW_PROXY\x10\x05\x12\x1b\n" +
	"\x17HOOK_NAME_ON_NEW_SERVER\x10\x06\x12\x17\n" +
	"\x13HOOK_NAME_ON_SIGNAL\x10\a\x12\x14\n" +
	"\x10HOOK_NAME_ON_RUN\x10\b\x12\x18\n" +
	"\x14HOOK_NAME_ON_BOOTING\x10\t\x12\x17\n" +
	"\x13HOOK_NAME_ON_BOOTED\x10\n" +
	"\x12\x18\n" +
	"\x14HOOK_NAME_ON_OPENING\x10\v\x12\x17\n" +
	"\x13HOOK_NAME_ON_OPENED\x10\f\x12\x18\n" +
	"\x14HOOK_NAME_ON_CLOSING\x10\r\x12\x17\n" +
	"\x13HOOK_NAME_ON_CLOSED\x10\x0e\x12\x18\n" +
	"\x14HOOK_NAME_ON_TRAFFIC\x10\x0f\x12$\n" +
	" HOOK_NAME_ON_TRAFFIC_FROM_CLIENT\x10\x10\x12\"\n" +
	"\x1eHOOK_NAME_ON_TRAFFIC_TO_SERVER\x10\x11\x12$\n" +
	" HOOK_NAME_ON_TRAFFIC_FROM_SERVER\x10\x12\x12\"\n" +
	"\x1eHOOK_NAME_ON_TRAFFIC_TO_CLIENT\x10\x13\x12\x19\n" +
	"\x15HOOK_NAME_ON_SHUTDOWN\x10\x14\x12\x15\n" +
	"\x11HOOK_NAME_ON_TICK\x10\x15\x12\x15\n" +
	"\x11HOOK_NAME_ON_HOOK\x10\x162\xd5\t\n" +
	"\x15GatewayDPluginService\x127\n" +
	"\x0fGetPluginConfig\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x126\n" +
	"\x0eOnConfigLoaded\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x123\n" +
	"\vOnNewLogger\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x121\n" +
	"\tOnNewPool\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x123\n" +
	"\vOnNewClient\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x122\n" +
	"\n" +
	"OnNewProxy\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x123\n" +
	"\vOnNewServer\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x120\n" +
	"\bOnSignal\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x12-\n" +
	"\x05OnRun\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x121\n" +
	"\tOnBooting\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x120\n" +
	"\bOnBooted\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x121\n" +
	"\tOnOpening\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x120\n" +
	"\bOnOpened\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x121\n" +
	"\tOnClosing\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x120\n" +
	"\bOnClosed\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x121\n" +
	"\tOnTraffic\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x12;\n" +
	"\x13OnTrafficFromClient\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x129\n" +
	"\x11OnTrafficToServer\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x12;\n" +
	"\x13OnTrafficFromServer\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x129\n" +
	"\x11OnTrafficToClient\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x122\n" +
	"\n" +
	"OnShutdown\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x12.\n" +
	"\x06OnTick\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.Struct\x12.\n" +
	"\x06OnHook\x12\x11.plugin.v1.Struct\x1a\x11.plugin.v1.StructB6Z4github.com/gatewayd-io/gatewayd-plugin-sdk/plugin/v1b\x06proto3"

var (
	file_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_plugin_v1_plugin_proto_rawDescData []byte
)

func file_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_plugin_v1_plugin_proto_rawDescData
}

var file_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plugin_v1_plugin_proto_goTypes = []any{
	(HookName)(0),        // 0: plugin.v1.HookName
	(*PluginID)(nil),     // 1: plugin.v1.PluginID
	(*PluginConfig)(nil), // 2: plugin.v1.PluginConfig
	nil,                  // 3: plugin.v1.PluginConfig.ConfigEntry
	nil,                  // 4: plugin.v1.PluginConfig.RequiresEntry
	(*Struct)(nil),       // 5: plugin.v1.Struct
}
var file_plugin_v1_plugin_proto_depIdxs = []int32{
	1,  // 0: plugin.v1.PluginConfig.id:type_name -> plugin.v1.PluginID
	3,  // 1: plugin.v1.PluginConfig.config:type_name -> plugin.v1.PluginConfig.ConfigEntry
	0,  // 2: plugin.v1.PluginConfig.hooks:type_name -> plugin.v1.HookName
	4,  // 3: plugin.v1.PluginConfig.requires:type_name -> plugin.v1.PluginConfig.RequiresEntry
	5,  // 4: plugin.v1.GatewayDPluginService.GetPluginConfig:input_type -> plugin.v1.Struct
	5,  // 5: plugin.v1.GatewayDPluginService.OnConfigLoaded:input_type -> plugin.v1.Struct
	5,  // 6: plugin.v1.GatewayDPluginService.OnNewLogger:input_type -> plugin.v1.Struct
	5,  // 7: plugin.v1.GatewayDPluginService.OnNewPool:input_type -> plugin.v1.Struct
	5,  // 8: plugin.v1.GatewayDPluginService.OnNewClient:input_type -> plugin.v1.Struct
	5,  // 9: plugin.v1.GatewayDPluginService.OnNewProxy:input_type -> plugin.v1.Struct
	5,  // 10: plugin.v1.GatewayDPluginService.OnNewServer:input_type -> plugin.v1.Struct
	5,  // 11: plugin.v1.GatewayDPluginService.OnSignal:input_type -> plugin.v1.Struct
	5,  // 12: plugin.v1.GatewayDPluginService.OnRun:input_type -> plugin.v1.Struct
	5,  // 13: plugin.v1.GatewayDPluginService.OnBooting:input_type -> plugin.v1.Struct
	5,  // 14: plugin.v1.GatewayDPluginService.OnBooted:input_type -> plugin.v1.Struct
	5,  // 15: plugin.v1.GatewayDPluginService.OnOpening:input_type -> plugin.v1.Struct
	5,  // 16: plugin.v1.GatewayDPluginService.OnOpened:input_type -> plugin.v1.Struct
	5,  // 17: plugin.v1.GatewayDPluginService.OnClosing:input_type -> plugin.v1.Struct
	5,  // 18: plugin.v1.GatewayDPluginService.OnClosed:input_type -> plugin.v1.Struct
	5,  // 19: plugin.v1.GatewayDPluginService.OnTraffic:input_type -> plugin.v1.Struct
	5,  // 20: plugin.v1.GatewayDPluginService.OnTrafficFromClient:input_type -> plugin.v1.Struct
	5,  // 21: plugin.v1.GatewayDPluginService.OnTrafficToServer:input_type -> plugin.v1.Struct
	5,  // 22: plugin.v1.GatewayDPluginService.OnTrafficFromServer:input_type -> plugin.v1.Struct
	5,  // 23: plugin.v1.GatewayDPluginService.OnTrafficToClient:input_type -> plugin.v1.Struct
	5,  // 24: plugin.v1.GatewayDPluginService.OnShutdown:input_type -> plugin.v1.Struct
	5,  // 25: plugin.v1.GatewayDPluginService.OnTick:input_type -> plugin.v1.Struct
	5,  // 26: plugin.v1.GatewayDPluginService.OnHook:input_type -> plugin.v1.Struct
	5,  // 27: plugin.v1.GatewayDPluginService.GetPluginConfig:output_type -> plugin.v1.Struct
	5,  // 28: plugin.v1.GatewayDPluginService.OnConfigLoaded:output_type -> plugin.v1.Struct
	5,  // 29: plugin.v1.GatewayDPluginService.OnNewLogger:output_type -> plugin.v1.Struct
	5,  // 30: plugin.v1.GatewayDPluginService.OnNewPool:output_type -> plugin.v1.Struct
	5,  // 31: plugin.v1.GatewayDPluginService.OnNewClient:output_type -> plugin.v1.Struct
	5,  // 32: plugin.v1.GatewayDPluginService.OnNewProxy:output_type -> plugin.v1.Struct
	5,  // 33: plugin.v1.GatewayDPluginService.OnNewServer:output_type -> plugin.v1.Struct
	5,  // 34: plugin.v1.GatewayDPluginService.OnSignal:output_type -> plugin.v1.Struct
	5,  // 35: plugin.v1.GatewayDPluginService.OnRun:output_type -> plugin.v1.Struct
	5,  // 36: plugin.v1.GatewayDPluginService.OnBooting:output_type -> plugin.v1.Struct
	5,  // 37: plugin.v1.GatewayDPluginService.OnBooted:output_type -> plugin.v1.Struct
	5,  // 38: plugin.v1.GatewayDPluginService.OnOpening:output_type -> plugin.v1.Struct
	5,  // 39: plugin.v1.GatewayDPluginService.OnOpened:output_type -> plugin.v1.Struct
	5,  // 40: plugin.v1.GatewayDPluginService.OnClosing:output_type -> plugin.v1.Struct
	5,  // 41: plugin.v1.GatewayDPluginService.OnClosed:output_type -> plugin.v1.Struct
	5,  // 42: plugin.v1.GatewayDPluginService.OnTraffic:output_type -> plugin.v1.Struct
	5,  // 43: plugin.v1.GatewayDPluginService.OnTrafficFromClient:output_type -> plugin.v1.Struct
	5,  // 44: plugin.v1.GatewayDPluginService.OnTrafficToServer:output_type -> plugin.v1.Struct
	5,  // 45: plugin.v1.GatewayDPluginService.OnTrafficFromServer:output_type -> plugin.v1.Struct
	5,  // 46: plugin.v1.GatewayDPluginService.OnTrafficToClient:output_type -> plugin.v1.Struct
	5,  // 47: plugin.v1.GatewayDPluginService.OnShutdown:output_type -> plugin.v1.Struct
	5,  // 48: plugin.v1.GatewayDPluginService.OnTick:output_type -> plugin.v1.Struct
	5,  // 49: plugin.v1.GatewayDPluginService.OnHook:output_type -> plugin.v1.Struct
	27, // [27:50] is the sub-list for method output_type
	4,  // [4:27] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_v1_plugin_proto_init() }
func file_plugin_v1_plugin_proto_init() {
	if File_plugin_v1_plugin_proto != nil {
		return
	}
	file_plugin_v1_struct_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1_plugin_proto = out.File
	file_plugin_v1_plugin_proto_goTypes = nil
	file_plugin_v1_plugin_proto_depIdxs = nil
}
